name: On Push

on: [push]

# Note that while this package supports both Linux and MacOS, for some reason the
# GitHub API will not work from the GitHub Mac VMs. Hence we only run the CI on
# Linux.
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Setup Python
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Extras
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      run: |
        python3 -m pip install --user --upgrade pip wheel setuptools
        python3 -m pip install behave
        sudo ./install-ninka.sh /usr/local

    - name: Run tests
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && !startsWith(github.ref, 'refs/tags/')
      run: |
        git submodule update --init --recursive
        make install
        make check

    - name: Static Analysis
      if: |
        !startsWith(github.event.head_commit.message, 'WIP')
        && startsWith(github.ref, 'refs/heads/feature/')
      run: |
        python3 -m pip install pylint
        make analyze
